version: '1'

services:
  backend:
    build: ./backend
    container_name: cocktail_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: cocktail_front
    ports:
      - "5173:5173"
    depends_on:
      - backend